### PR TITLE
Support Pydantic Models

### PR DESCRIPTION
**Pull request by rodfersou**
Don't treat Pydantic Model classes as Iterable
Change needed for Pydantic Model classes works with `extracting` method

### CODE REVIEW

**Comment by saturnboy** [comment]
@rodfersou assertpy is pure python with zero non-standard dependencies.  appreciate the effort, but it won't be supporting any non-standard libraries like Pydantic.

**Comment by saturnboy** [comment]
@rodfersou added better `namedtuple` support in 8e6c679...if that still doesn't fit your needs, please reopen this PR with "no dependency" code

**Comment by rodfersou** [comment]
@saturnboy well, it works for namedtuple now, but not for pydantic models, just tried and failed..

is it possible to invert the logic and try extract as an object first? this would fix my problem

**Comment by nadworny** [comment]
I would also love support for pydantic models... Is it possible to have "no dependency" code but still support it?

**Pull request closed without merging**
